### PR TITLE
prefer named export

### PR DESCRIPTION
**Pull request by aaccurso**

### CODE REVIEW

**Comment by mAAdhaTTah** [comment]
Two things about this:

There's a plugin that does this already. 

I'm thumbs-down on this rule. I generally prefer default exports.

**Review by mAAdhaTTah — APPROVED** [review]
After conversation on Slack, I'm in favor of merging this but opposed to making this rule the default for the Valtech config (for now at least). No changes needed.

**Comment by aaccurso** [comment]
I'll decline this in favor of a rule similar to `prefer-default-import-as-filename` and `prefer-default-export-as-filename`. I found this plugin that seems to be what I'm looking for: https://github.com/selaux/eslint-plugin-filenames

**Comment by mAAdhaTTah** [comment]
That matches up with exports but not imports. I bet we could use that as a template for a similar import plugin.

**Comment by aaccurso** [comment]
Yes, I'll experiment with this. Thanks!

**Pull request closed without merging**
